### PR TITLE
Bot initialization and Environment File

### PR DESCRIPTION
**Pull request by etsai7**
1. Creating bot intialization code with simple logon message when successfully connected. 
2. Added `env.py` with variables that will contain eventual credentials. Do not commit with credentials
3. Updated `requirements.txt` to include `discord-interactions-py` library and a requirement that Python 3.10+ is used for compatibility

### CODE REVIEW

**Review by goldrik — COMMENTED** [review]
Just some minor suggestions. Your input is also valuable

- Bot name idea: Grendel
- maple_bot.py -> bot.py?
- resources/ should be outside of src/
- ReadMe -> README
- Add bs4 to "Packages" in README
- maple_ranking/ -> utils/ ?

**Comment by etsai7** [comment]
Refactored most of it, though I think for the last point, I was going to keep it as maple_ranking for code specific to ranking commands and logic. Was thinking of creating new folders for new commands and grouping them together like that. What do you think?

**Review by goldrik — APPROVED** [review]
The changes in question appear to be satisfactory at this present stage in development.

**Comment by goldrik** [comment]
lgtm

**Pull request merged**
